### PR TITLE
Dynamic url feature

### PR DESCRIPTION
**Pull request by ghbutton**
This will give the library the ability to pass the url with the function call in order to connect to more than one node for an application

### CODE REVIEW

**Comment by ayrat555** [comment]
@ghbutton good work. Can you bump version in `mix.exs` and `README` and add your changes to Changelog?

**Comment by ghbutton** [comment]
@ayrat555 Updated

**Comment by ayrat555** [comment]
@ghbutton https://www.hex.pm/packages/ethereumex/0.3.3

**Comment by ghbutton** [comment]
🤩🧡

**Pull request merged**
